name: nourish_link
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core Services
  firebase_core: ^3.2.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.0.2

  # Core Feature Dependencies
  google_maps_flutter: ^2.6.1 # For Geolocation & Mapping (Phase 2)
  geolocator: ^12.0.0 # For getting real-time GPS location
  firebase_messaging: ^15.0.1 # For Push Notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
